### PR TITLE
adding requirements.txt for example_folder

### PR DESCRIPTION
**Pull request by someshfengde**
adding requirements for example_folder will help us to run the application more easily ( before we have to install required modules separately) 
we can now just do `pip install -r requirements.txt` and pip will install dependencies for us.

### CODE REVIEW

**Comment by jonasvdd** [comment]
Hi @someshfengde 👋🏼!

Thank you for contributing, very valid PR!
I think this can indeed be added, however I would opt to 
* omit the required packages which are already listed in our pyproject.toml ⬇️ 

  https://github.com/predict-idlab/plotly-resampler/blob/cc951c14c26fbef91678e76017a2f4a94bfd09fb/pyproject.toml#L11-L20

**Comment by someshfengde** [comment]
but if we omit those packages then we cannot run get requirements from one file. Either we can add these additional requirements in `.toml` file or we can have it here in requirements.txt 
(I've made PR just considering the dash-examples folder so there might be more libraries which required)

**Comment by jonasvdd** [comment]
Hi @someshfengde!

I discussed this with @jvdd and he was rather fond of adding these requirements to the poetry dev dependencies. (As otherwise, we would have multiple dependency management systems.) ⬇️ 

https://github.com/predict-idlab/plotly-resampler/blob/cc951c14c26fbef91678e76017a2f4a94bfd09fb/pyproject.toml#L21-L39

But then we made the observation that most users do not at all need / use  `poetry`, so your requirements.txt makes a lot of sense! 😄 

However, we might want to:
- [ ] loosen the (version locked) requirements of your packages
- [ ]  also add the requirements of all the other example scripts/notebooks 
- [ ] add the install command in the examples its readme.md

**Comment by someshfengde** [comment]
yes I've also seen using poetry first time :smile: 
yes sure 
Should I loosen up version lock and and make PR again?

**Comment by jonasvdd** [comment]
I think you can just re-use this PR and adjust the version lock!

**Comment by someshfengde** [comment]
ohh thanks

**Comment by someshfengde** [comment]
Hi I've changed and loosened up a requirements a little bit 
For now it's working fine on My Linux system (both dash app and plotly-resampler is working) 

We can add installation instructions in readme.md file itself ( I haven't added it not sure if we should add this or not? )

**Comment by jonasvdd** [comment]
Will close this PR as this will be handled in #104

**Pull request closed without merging**
