### PR TITLE
✨  add confidence bound example + more figure retention in `basic_example.py`.

### PR DESCRIPTION
**Pull request by jonasvdd**
* Adds the confidence bound example of #158 
* Figure output should now be retained significantly more (introduced the `use_png` argument).
Also:
* remove code-quality badge, as in #165

### CODE REVIEW

**Comment by jvdd** [comment]
LGTM! Not really sure tho if #120 is resolved, still seemed quite slow when testing this..

Might go over the notebook a 2nd time later today

**Comment by jvdd** [comment]
We can include the `datetime` index when using plotly(-resampler) as pandas plotting backend - as #120 is +/- resolved.

**Comment by jvdd** [comment]
The notebook is currently a colorbook of different plotting templates / themes. We might stay consistent and either use 1 theme or none. If we use one, I think the cleanest solution would be to define a variable at the top that defines the theme.

**Comment by jonasvdd** [comment]
Well, I'm kinda fond of using various different options to create the figures; as this shows that plotly-resampler does not impose many restrictions upon plotly.

**Review by jvdd — APPROVED** [review]

**Pull request merged**
