### PR TITLE
Only Update Visible Traces

### LINKED ISSUE #21: Resample only the visible traces
Only resample the traces that are shown, and do not resample the not shown (i.e., toggled off) traces.

This is not straightforward, as toggling a trace in the legend does not result in a callback event (i.e., pure front-end event).  
To fix this, we should pass the visibility state of the front-end via the trace-updater. Needs some more thought..

### PR DESCRIPTION
**Pull request by jayceslesar**
Ideally closes #21

### CODE REVIEW

**Comment by jayceslesar** [comment]
Kindof tricky to test -- was hoping to get some interactivity with some print statements inside of a dash app, but alas adding a print after the continue statement where I added to the if clause gives me nothing

**Comment by jayceslesar** [comment]
I assume this is failing because of the `visible="legendonly"` in lines 317 and 355 in `tests/conftest.py` ?

**Comment by jvdd** [comment]
Thanks for this contribution @jayceslesar! Your code looks clean :smile: 

I'll manually test it some more & add a couple of tests (for both the FigureResampler & FigureWidgetResampler). Feel free to do this yourself!

PS: The failing test is because we toggle some traces (making them unvisible) and check whether all traces gets resampled (which since this PR will not be the case anymore :tada:)

**Comment by jvdd** [comment]
Hey @jayceslesar 

I experimented today a little bit with your code and found out that it does not work as desired. 
Our desired behavior is that after toggling traces off in the front-end (i.e., making them invisible), they should not be resampled until they are toggled on again (i.e., making them again visible).

Your implementation does not result in this desired behavior as we have no (currently) access in the back-end to the front-end state. I think fixing this is not really convenient... 

(perhaps @jonasvdd could also chime in with his opinion)

**Comment by jayceslesar** [comment]
> Your implementation does not result in this desired behavior as we have no (currently) access in the back-end to the front-end state. I think fixing this is not really convenient...

I wonder what the path forward there is, guess I would need more understanding of where the difference between the back end and the front end state exists

**Comment by jonasvdd** [comment]
@jayceslesar,

I created a first implementation on this branch https://github.com/predict-idlab/trace-updater/tree/update_visible of `trace_updater`. This is a rather naive implementation, as all data still gets resampled at the same time in the back-end. 

Will give a more elaborate update sometime later.

**Comment by jonasvdd** [comment]
@jayceslesar, @jvdd, If you are all okay with this; I will close this (legacy) PR, and we will handle this in a future PR! A thesis student of ours (with some help of us) managed to create this functionality. Ideally, this will be added this summer to plotly-resampler! 🔥

**Comment by jvdd** [comment]
Closing is fine for me! @jonasvdd @jayceslesar

**Comment by jonasvdd** [comment]
Okay, will close it!

**Pull request closed without merging**
