### PR TITLE
:zap: Improving callbacks

### PR DESCRIPTION
**Pull request by jonasvdd**
Still TODO:

- [x] create a new version
- [x] redeploy on pypi (with GitHub readme)

### CODE REVIEW

**Comment by jvdd** [comment]
@jonasvdd can I redeploy new pypi version?

**Comment by jonasvdd** [comment]
@jvdd what do you think of the default downsampler argument,
do we set `interleave_gaps` by default to `True` or not?

**Review by jvdd — COMMENTED** [review]
Nice work :muscle:

**Comment by jvdd** [comment]
> @jvdd what do you think of the default downsampler argument, do we set `interleave_gaps` by default to `True` or not?

Should be `True` imo; also documented this in the latest commit :smile:

**Pull request merged**
