### PR TITLE
Update pyproject.toml

### PR DESCRIPTION
**Pull request by bbradbury**
I think this is a safe change - lttbc has been updated to 0.2.1

### CODE REVIEW

**Comment by jvdd** [comment]
Hi, 

Thanks for your contribution! :smile: 

I would love to merge it into main, but there seems to be a problem with lttbc 0.2.1 (see #42). The compiled files use a numpy version that is rather recent, resulting in warnings for the current numpy versions plotly-resampler supports.

I'm interested to hear your thoughts about this!

Cheers, 
Jeroen

PS: @jonasvdd  is currently looking into implementing & compiling a more optimized version of lttbc :rocket:

**Comment by zxweed** [comment]
Another evidence of lttbc's problematic behavior is that a strange error occurs when you try to deploy the configuration to binder:

```
Collecting lttbc==0.1.9
  Downloading lttbc-0.1.9.tar.gz (4.4 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /srv/conda/envs/notebook/bin/python3.8 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-uhjh_3bk/lttbc_640214e8567d4d14a66351971e1a2f74/setup.py'"'"'; __file__='"'"'/tmp/pip-install-uhjh_3bk/lttbc_640214e8567d4d14a66351971e1a2f74/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-faa8ruak
       cwd: /tmp/pip-install-uhjh_3bk/lttbc_640214e8567d4d14a66351971e1a2f74/
  Complete output (5 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-uhjh_3bk/lttbc_640214e8567d4d14a66351971e1a2f74/setup.py", line 7, in <module>
      import numpy
  ModuleNotFoundError: No module named 'numpy'
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/b1/56/92bd8ddf5ffa4ba46b5d818c5243e4912443d3aa8bf72ec5a190828ea0d9/lttbc-0.1.9.tar.gz#sha256=35b375c4fd26c358f33f9a8f579024e5596cde0ed90e33f8be105af26fab8951 (from https://pypi.org/simple/lttbc/) (requires-python:>=3.5). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement lttbc==0.1.9 (from versions: 0.1.9, 0.2.0, 0.2.1)
ERROR: No matching distribution found for lttbc==0.1.9
```
So I very much appreciate the attempt to replace this package with the potentially more efficient fast-lttb.

**Comment by jonasvdd** [comment]
Hi,

Some problems with `lttbc` already popped up in #65, #32 and #42.

As @jvdd already mentioned, I'm currently looking into implementing the core components of [EfficientLTTB](https://github.com/predict-idlab/plotly-resampler/blob/0fda64cbfdebf37ea649099e6b5ef2e4bbc751ec/plotly_resampler/aggregation/aggregators.py#L263) in c, see [this repo](https://github.com/jonasvdd/lttbc). However, I cannot estimate how long this will take (have some other deadlines / trips coming up the next weeks), as I do not have much experience in compiling platform-agnostic python bindings for c code (which seems one of the major problems now with `lttbc`). So if you have any experience regarding that, feel free to help me out!

@zxweed, from your error it seems that `lttbc` requires `numpy`, so maybe you can circumvent this by first (explicitly) installing `numpy` in your python environment after which you try to add `lttbc`? (I'm also intrigued by the lttbc-version *0.1.9*, as our `pyproject.toml` now states `lttbc=0.2.0`, which is a strict version requirement)

**Comment by jonasvdd** [comment]
@zxweed, If you look at the original `lttbc` repo, the [requirements.txt](https://github.com/dgoeries/lttbc/blob/bfb04a4fdf4478408b86d5728268e50298d79d5a/requirements.txt) lists `numpy>=1.16`. So I would guess that the `lttbc` python bindings were generated with the `numpy` 1.16 python-C version. And this might cause the incompatibility with later /prior `numpy` versions.

**Comment by bbradbury** [comment]
Thanks @jonasvdd  @zxweed! Understood on the wackiness with the new version of lttbc. If I get cycles I will have a look at the EfficientLTTB code and I will also socialize it with my team at work in case anyone here can help.

**Comment by jonasvdd** [comment]
Hi @bbradbury

In this PR #84, I am to add my own LTTB implementation to plotly-resampler with the aim of (1) reducing install errors and (2) adding optimized implementations of this algorithm. 

Feel free to take a look / give some thoughts if you have time.
Additionally, plotly-resamplers' license was changed to `MIT` 🥳

**Pull request closed without merging**
