### PR TITLE
👷 build: create codeql.yml

### PR DESCRIPTION
**Pull request by NielsPraet**
Adds github code scanning to the repository.

### CODE REVIEW

**Comment by jonasvdd** [comment]
@NielsPraet good work! 

Maybe you can also add the CI filter that the `unit` tests only runs when there are new changes are made to the:
- `tests` directory
- `plotly_resampler` directory
- `poetry.lock`

@jvdd - please correct me when I'm missing something!

**Comment by jonasvdd** [comment]
resolves #157

**Comment by jvdd** [comment]
Perhaps also `poetry.toml` and the `Makefile` @jonasvdd?

**Comment by jonasvdd** [comment]
@jvdd, why the `poetry.toml` and the `makefile`? 

The poetry.lock should be directly affected by the `pyproject.toml` right? 
When looking at the `test.yml` It appears that the makefile is not utilized by the tesing?

**Comment by jonasvdd** [comment]
nice! :)

**Comment by jonasvdd** [comment]
LGTM! :)

**Review by jonasvdd — APPROVED** [review]

**Review by jvdd — APPROVED** [review]

**Pull request merged**
